/* ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 *  AUTO-GENERATED FROM tsh-api/src/client/vision-client.ts
 *  DO NOT EDIT IN THIS APP — edits will be overwritten.
 *  To change: edit the source in tsh-api, then run:
 *    /var/www/tsh-api/scripts/sync-vision-client.sh --apply
 *  synced-at: 2026-04-22T12:08:39Z
 * ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ */
/**
 * ═══════════════════════════════════════════════════════════════════════════
 *  TSH Vision Client SDK — canonical source of truth
 * ═══════════════════════════════════════════════════════════════════════════
 *
 * This file is the SINGLE SOURCE OF TRUTH for how TSH apps talk to the
 * vision service (port 3003) through the central API gateway (port 3010).
 *
 * ░░░ DO NOT EDIT THIS FILE IN INDIVIDUAL APPS ░░░
 * Edit it here in tsh-api, then run: ./scripts/sync-vision-client.sh
 *
 * Apps that include a copy:
 *   - tsh-pos         -> src/lib/vision-client.ts
 *   - tsh-rep-app     -> src/lib/vision-client.ts
 *   - tsh-admin       -> src/lib/vision-client.ts
 *   - tsh-aftersale   -> src/lib/vision-client.ts
 *   - tsh-clients     -> src/lib/vision-client.ts
 *   - tsh-inventory   -> src/lib/vision-client.ts
 *
 * All network calls route through the gateway (/api/vision/*) — apps must
 * NEVER call tsh-vision directly on port 3003.
 *
 * ── Quick start ────────────────────────────────────────────────────────────
 *
 *   import { createVisionClient } from '@/lib/vision-client';
 *
 *   const vision = createVisionClient({
 *     userId: session.user.uid,
 *     appSource: 'rep-app',
 *   });
 *
 *   const result = await vision.recognize(base64Image);
 *   if (result.is_new) { ... } else { ... }
 *
 * ───────────────────────────────────────────────────────────────────────────
 */

// ─── Config ────────────────────────────────────────────────────────────────

const GATEWAY_URL = process.env.GATEWAY_URL ?? 'http://127.0.0.1:3010';
const GATEWAY_API_KEY = process.env.GATEWAY_API_KEY ?? '';

const DEFAULT_TIMEOUTS = {
  recognize: 45000,
  feedback: 10000,
  enhance: 60000,
  galleryStats: 5000,
  productGallery: 8000,
  classify: 15000,
} as const;

// ─── Types ─────────────────────────────────────────────────────────────────

/**
 * Gemini-extracted context about what's on the image. Used by active learning
 * (Phase 7.2b) — when the user confirms a match, these tokens are mined to
 * build semantic aliases.
 */
export interface DetectedContext {
  type?: string | null;
  brand?: string | null;
  model?: string | null;
  voltage?: string | null;
  amperage?: string | null;
  wattage?: string | null;
  visibleText?: string | null;
}

export interface VisionMatch {
  id: number;
  name: string;
  similarity: number; // 0-100
  has_image?: boolean;
}

/**
 * Raw Gemini vision block as the backend emits it. Snake-case preserved.
 * Apps usually consume the pre-normalized `detected` field instead.
 */
export interface RawVisionBlock {
  product_type?: string | null;
  brand?: string | null;
  model?: string | null;
  voltage?: string | null;
  amperage?: string | null;
  wattage?: string | null;
  connector_size?: string | null;
  color?: string | null;
  size_or_length?: string | null;
  channels?: string | null;
  resolution?: string | null;
  visible_text?: string | null;
  description?: string | null;
  confidence?: number | null;
  [key: string]: unknown; // forward-compat for new fields
}

export interface RecognizeResponse {
  suggested_name: string;
  suggested_category: string;
  suggested_category_id: number | null;
  description: string;
  confidence: 'high' | 'medium' | 'low';
  existing_matches: VisionMatch[];
  is_new: boolean;
  is_non_product: boolean;
  brand?: string;
  model?: string;
  specs?: Record<string, string | null>;
  alternative_names?: string[];
  naming_rationale?: string;
  /** Pre-normalized Gemini detection (camelCase). Primary consumer surface. */
  detected: DetectedContext | null;
  /** Raw backend `vision` block — kept for forward-compat / advanced callers. */
  vision?: RawVisionBlock;
  /** Round-trip ms reported by the vision service. */
  elapsed_ms?: number;
}

export interface FeedbackPayload {
  /** Product the AI originally suggested (top match). */
  selectedProductId: number;
  /** If the user picked a DIFFERENT product than the AI's top, pass it here. */
  correctProductId?: number | null;
  /** Base64-encoded image (with or without data: prefix). */
  imageData: string;
  /** Optional client-side hash for dedup tracking. */
  imageHash?: string;
  /** Free-form tag describing the confirmation surface (e.g. "pos_inventory_confirm"). */
  engine?: string;
  /** Gemini detection snapshot — enables server-side alias learning. */
  visionHint?: DetectedContext | null;
}

export interface GalleryStats {
  total_products_with_gallery: number;
  total_images: number;
  avg_per_product: number;
  best_quality_score: number;
  updated_at?: string;
}

export interface VisionClientOptions {
  /** User id for auditing — included as x-user-id header. */
  userId?: string | number;
  /** Which app is calling — 'pos' | 'rep-app' | 'admin' | 'aftersale' | 'clients'. */
  appSource?: string;
  /** Override default timeouts in milliseconds. */
  timeouts?: Partial<typeof DEFAULT_TIMEOUTS>;
  /** Alternative gateway URL (rarely needed — defaults to env var). */
  gatewayUrl?: string;
}

// ─── Errors ────────────────────────────────────────────────────────────────

export class VisionError extends Error {
  constructor(
    public readonly reason: string,
    public readonly status: number,
    public readonly details?: string,
  ) {
    super(`[VisionError ${status}] ${reason}${details ? ` — ${details}` : ''}`);
    this.name = 'VisionError';
  }
}

// ─── Factory ───────────────────────────────────────────────────────────────

export function createVisionClient(opts: VisionClientOptions = {}) {
  const baseUrl = opts.gatewayUrl ?? GATEWAY_URL;
  const timeouts = { ...DEFAULT_TIMEOUTS, ...(opts.timeouts ?? {}) };

  const buildHeaders = (): Record<string, string> => ({
    'Content-Type': 'application/json',
    'x-api-key': GATEWAY_API_KEY,
    ...(opts.userId !== undefined ? { 'x-user-id': String(opts.userId) } : {}),
    ...(opts.appSource ? { 'x-app-source': opts.appSource } : {}),
  });

  async function gatewayFetch(
    path: string,
    body: unknown | null,
    timeoutMs: number,
    method: 'GET' | 'POST' = 'POST',
  ): Promise<any> {
    let res: Response;
    try {
      res = await fetch(`${baseUrl}${path}`, {
        method,
        headers: buildHeaders(),
        ...(body !== null ? { body: JSON.stringify(body) } : {}),
        signal: AbortSignal.timeout(timeoutMs),
      });
    } catch (err: any) {
      if (err?.name === 'TimeoutError' || err?.name === 'AbortError') {
        throw new VisionError('timeout', 504, `${timeoutMs}ms elapsed on ${path}`);
      }
      throw new VisionError('network', 503, String(err?.message ?? err));
    }
    if (!res.ok) {
      let detail = '';
      try { detail = (await res.text()).slice(0, 300); } catch { /* ignore */ }
      throw new VisionError('gateway_error', res.status, detail);
    }
    try {
      return await res.json();
    } catch (err: any) {
      throw new VisionError('invalid_json', 500, String(err?.message ?? err));
    }
  }

  return {
    /**
     * Identify a product from a base64 image. Runs the full pipeline:
     * CLIP fast-path → Gemini vision → Model-First Retrieval → semantic aliases.
     *
     * @param base64Image - Either a raw base64 string or a data URL (both accepted)
     * @returns Normalized RecognizeResponse. Caller should inspect `is_new`, `is_non_product`, and `existing_matches`.
     * @throws VisionError on network, timeout, or invalid response.
     */
    async recognize(base64Image: string): Promise<RecognizeResponse> {
      const data = await gatewayFetch(
        '/api/vision/recognize',
        { image: base64Image },
        timeouts.recognize,
      );
      if (!data?.success || !data?.data) {
        throw new VisionError('empty_response', 500, JSON.stringify(data).slice(0, 200));
      }
      return normalizeRecognize(data.data, data.elapsed_ms);
    },

    /**
     * Send confirmation/correction feedback after user interacts with a scan result.
     * Fire-and-forget recommended — callers should catch errors silently.
     *
     * Backend behavior:
     *   - Saves image to product_gallery/{pid}/images/ with quality scoring
     *   - Records signal in feedback SQLite for CLIP re-rank boosting
     *   - Learns semantic aliases from visionHint (Phase 7.2b)
     */
    async sendFeedback(payload: FeedbackPayload): Promise<{ success: boolean; details?: string }> {
      try {
        await gatewayFetch('/api/vision/feedback', payload, timeouts.feedback);
        return { success: true };
      } catch (err: any) {
        // Feedback is optional — return structured failure instead of throwing
        return {
          success: false,
          details: err instanceof VisionError ? err.message : String(err),
        };
      }
    },

    /**
     * Enhance a product image (white background, square crop, quality boost).
     * Used by the product-registration flow to normalize user-captured photos
     * before storing as the Odoo primary image.
     */
    async enhance(
      base64Image: string,
      options?: { white_background?: boolean; square_crop?: boolean; enhance?: boolean; target_size?: number },
    ): Promise<{ image: string; metadata?: Record<string, any> }> {
      const data = await gatewayFetch(
        '/api/vision/enhance',
        { image: base64Image, options: options ?? {} },
        timeouts.enhance,
      );
      // Backend returns { success, enhanced_image, original_size, final_size, ... }
      // (NOT wrapped under data.image — this was a long-standing mismatch.)
      if (!data?.success || !data?.enhanced_image) {
        throw new VisionError('enhance_failed', 500, JSON.stringify(data).slice(0, 200));
      }
      return {
        image: data.enhanced_image,
        metadata: {
          original_size: data.original_size,
          final_size: data.final_size,
          file_size_kb: data.file_size_kb,
          elapsed_ms: data.elapsed_ms,
          enhancements_applied: data.enhancements_applied,
        },
      };
    },

    /**
     * Get global gallery statistics — how many products have training images,
     * total image count, average per product. Used by admin dashboards.
     */
    async getGalleryStats(): Promise<GalleryStats> {
      const data = await gatewayFetch(
        '/api/vision/gallery/stats',
        null,
        timeouts.galleryStats,
        'GET',
      );
      return (data?.data ?? data) as GalleryStats;
    },

    /**
     * List all gallery images for a specific product. Returns metadata
     * including quality_score and filename. Thumbnails fetched separately.
     */
    async getProductGallery(productId: number): Promise<{
      product_id: number;
      images: Array<{ filename: string; quality_score: number; url: string }>;
    }> {
      const data = await gatewayFetch(
        `/api/vision/gallery/${productId}`,
        null,
        timeouts.productGallery,
        'GET',
      );
      return data?.data ?? data;
    },

    /**
     * Classify an image against known product categories (AC Adapter, Battery,
     * Cable, etc). Used as a lightweight pre-filter before full recognize.
     */
    async classify(base64Image: string): Promise<{ category: string; confidence: number; alternatives: Array<{ category: string; confidence: number }> }> {
      const data = await gatewayFetch(
        '/api/vision/classify',
        { image: base64Image },
        timeouts.classify,
      );
      return data?.data ?? data;
    },

    /** Low-level escape hatch: direct gateway call with arbitrary path/body. */
    async raw(path: string, body: unknown | null, timeoutMs: number = 30000, method: 'GET' | 'POST' = 'POST'): Promise<any> {
      return gatewayFetch(path, body, timeoutMs, method);
    },
  };
}

// ─── Helpers ───────────────────────────────────────────────────────────────

function normalizeRecognize(data: any, elapsedMs?: number): RecognizeResponse {
  const vision = (data?.vision ?? {}) as RawVisionBlock;
  const specs = (data?.specs ?? {}) as Record<string, string | null>;
  const validConf = (['high', 'medium', 'low'] as const).includes(data?.confidence)
    ? data.confidence : 'medium';

  // Pre-normalize detection: vision block takes precedence, top-level is fallback.
  // Matches the logic that used to live inline in tsh-pos buildScanResult().
  const detected: DetectedContext = {
    type: (vision.product_type as string | null) ?? null,
    brand: (vision.brand as string | null) ?? (data?.brand ?? null),
    model: (vision.model as string | null) ?? (data?.model ?? null),
    voltage: (vision.voltage as string | null) ?? (specs.voltage ?? null),
    amperage: (vision.amperage as string | null) ?? (specs.amperage ?? null),
    wattage: (vision.wattage as string | null) ?? (specs.wattage ?? null),
    visibleText: (vision.visible_text as string | null) ?? null,
  };
  const hasAnyDetection =
    detected.type || detected.brand || detected.model ||
    detected.voltage || detected.amperage || detected.wattage;

  return {
    suggested_name: data?.suggested_name ?? 'Unknown Product',
    suggested_category: data?.suggested_category ?? 'accessories',
    suggested_category_id: data?.suggested_category_id ?? null,
    description: data?.description ?? '',
    confidence: validConf,
    existing_matches: Array.isArray(data?.existing_matches)
      ? data.existing_matches.map((m: any) => ({
          id: Number(m.id),
          name: String(m.name ?? ''),
          similarity: Number(m.similarity ?? 0),
          has_image: m.has_image === true,
        }))
      : [],
    is_new: data?.is_new ?? true,
    is_non_product: data?.is_non_product === true,
    brand: data?.brand ?? '',
    model: data?.model ?? '',
    specs,
    alternative_names: Array.isArray(data?.alternative_names) ? data.alternative_names : [],
    naming_rationale: data?.naming_rationale ?? '',
    detected: hasAnyDetection ? detected : null,
    vision,
    elapsed_ms: elapsedMs,
  };
}
