// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/[locale]" | "/[locale]/account-statement" | "/[locale]/cart" | "/[locale]/credit-notes" | "/[locale]/credit-notes/[id]" | "/[locale]/dashboard" | "/[locale]/deliveries" | "/[locale]/delivery-confirm" | "/[locale]/invoices" | "/[locale]/invoices/[id]" | "/[locale]/login" | "/[locale]/login/verify" | "/[locale]/notifications" | "/[locale]/orders" | "/[locale]/orders/[id]" | "/[locale]/orders/[id]/track" | "/[locale]/packages" | "/[locale]/payments" | "/[locale]/payments/[id]" | "/[locale]/products" | "/[locale]/profile" | "/[locale]/quotations" | "/[locale]/returns" | "/[locale]/returns/new" | "/[locale]/settings" | "/[locale]/shop" | "/[locale]/shop/[id]" | "/[locale]/shop/order-type" | "/[locale]/stock" | "/[locale]/support"
type AppRouteHandlerRoutes = "/api/ai/chat" | "/api/ai/embed" | "/api/ai/search" | "/api/auth/[...nextauth]" | "/api/auth/otp/send" | "/api/auth/otp/send-email" | "/api/auth/otp/verify" | "/api/auth/otp/verify-firebase" | "/api/auth/webauthn/auth-options" | "/api/auth/webauthn/auth-verify" | "/api/auth/webauthn/register-options" | "/api/auth/webauthn/register-verify" | "/api/checkout" | "/api/error-report" | "/api/health" | "/api/images/[itemId]" | "/api/mobile/auth/callback" | "/api/mobile/auth/login" | "/api/mobile/auth/session" | "/api/mobile/auth/verify" | "/api/mobile/cart/checkout" | "/api/mobile/categories" | "/api/mobile/credit-notes" | "/api/mobile/dashboard" | "/api/mobile/invoices" | "/api/mobile/invoices/[id]" | "/api/mobile/orders" | "/api/mobile/orders/[id]" | "/api/mobile/payments" | "/api/mobile/products" | "/api/mobile/products/[id]" | "/api/mobile/profile" | "/api/mobile/statement" | "/api/notifications" | "/api/orders/[orderId]/approve" | "/api/orders/[orderId]/delivery-confirm" | "/api/orders/[orderId]/receive" | "/api/orders/[orderId]/reject" | "/api/returns/submit" | "/api/revalidate" | "/api/stock/search" | "/api/sync/images" | "/api/sync/stock"
type PageRoutes = never
type LayoutRoutes = "/" | "/[locale]"
type RedirectRoutes = "/" | "/ar" | "/en"
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/[locale]": { "locale": string; }
  "/[locale]/account-statement": { "locale": string; }
  "/[locale]/cart": { "locale": string; }
  "/[locale]/credit-notes": { "locale": string; }
  "/[locale]/credit-notes/[id]": { "locale": string; "id": string; }
  "/[locale]/dashboard": { "locale": string; }
  "/[locale]/deliveries": { "locale": string; }
  "/[locale]/delivery-confirm": { "locale": string; }
  "/[locale]/invoices": { "locale": string; }
  "/[locale]/invoices/[id]": { "locale": string; "id": string; }
  "/[locale]/login": { "locale": string; }
  "/[locale]/login/verify": { "locale": string; }
  "/[locale]/notifications": { "locale": string; }
  "/[locale]/orders": { "locale": string; }
  "/[locale]/orders/[id]": { "locale": string; "id": string; }
  "/[locale]/orders/[id]/track": { "locale": string; "id": string; }
  "/[locale]/packages": { "locale": string; }
  "/[locale]/payments": { "locale": string; }
  "/[locale]/payments/[id]": { "locale": string; "id": string; }
  "/[locale]/products": { "locale": string; }
  "/[locale]/profile": { "locale": string; }
  "/[locale]/quotations": { "locale": string; }
  "/[locale]/returns": { "locale": string; }
  "/[locale]/returns/new": { "locale": string; }
  "/[locale]/settings": { "locale": string; }
  "/[locale]/shop": { "locale": string; }
  "/[locale]/shop/[id]": { "locale": string; "id": string; }
  "/[locale]/shop/order-type": { "locale": string; }
  "/[locale]/stock": { "locale": string; }
  "/[locale]/support": { "locale": string; }
  "/api/ai/chat": {}
  "/api/ai/embed": {}
  "/api/ai/search": {}
  "/api/auth/[...nextauth]": { "nextauth": string[]; }
  "/api/auth/otp/send": {}
  "/api/auth/otp/send-email": {}
  "/api/auth/otp/verify": {}
  "/api/auth/otp/verify-firebase": {}
  "/api/auth/webauthn/auth-options": {}
  "/api/auth/webauthn/auth-verify": {}
  "/api/auth/webauthn/register-options": {}
  "/api/auth/webauthn/register-verify": {}
  "/api/checkout": {}
  "/api/error-report": {}
  "/api/health": {}
  "/api/images/[itemId]": { "itemId": string; }
  "/api/mobile/auth/callback": {}
  "/api/mobile/auth/login": {}
  "/api/mobile/auth/session": {}
  "/api/mobile/auth/verify": {}
  "/api/mobile/cart/checkout": {}
  "/api/mobile/categories": {}
  "/api/mobile/credit-notes": {}
  "/api/mobile/dashboard": {}
  "/api/mobile/invoices": {}
  "/api/mobile/invoices/[id]": { "id": string; }
  "/api/mobile/orders": {}
  "/api/mobile/orders/[id]": { "id": string; }
  "/api/mobile/payments": {}
  "/api/mobile/products": {}
  "/api/mobile/products/[id]": { "id": string; }
  "/api/mobile/profile": {}
  "/api/mobile/statement": {}
  "/api/notifications": {}
  "/api/orders/[orderId]/approve": { "orderId": string; }
  "/api/orders/[orderId]/delivery-confirm": { "orderId": string; }
  "/api/orders/[orderId]/receive": { "orderId": string; }
  "/api/orders/[orderId]/reject": { "orderId": string; }
  "/api/returns/submit": {}
  "/api/revalidate": {}
  "/api/stock/search": {}
  "/api/sync/images": {}
  "/api/sync/stock": {}
  "/ar": {}
  "/en": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/[locale]": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
