// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/[locale]/(auth)/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/login">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(auth)/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(auth)/login/verify/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/login/verify">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(auth)/login/verify/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(main)/account-statement/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/account-statement">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(main)/account-statement/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(main)/credit-notes/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/credit-notes/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(main)/credit-notes/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(main)/credit-notes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/credit-notes">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(main)/credit-notes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(main)/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(main)/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(main)/deliveries/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/deliveries">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(main)/deliveries/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(main)/delivery-confirm/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/delivery-confirm">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(main)/delivery-confirm/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(main)/invoices/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/invoices/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(main)/invoices/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(main)/invoices/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/invoices">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(main)/invoices/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(main)/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/notifications">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(main)/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(main)/orders/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/orders/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(main)/orders/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(main)/orders/[id]/track/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/orders/[id]/track">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(main)/orders/[id]/track/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(main)/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/orders">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(main)/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(main)/packages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/packages">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(main)/packages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(main)/payments/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/payments/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(main)/payments/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(main)/payments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/payments">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(main)/payments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(main)/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/profile">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(main)/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(main)/quotations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/quotations">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(main)/quotations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(main)/returns/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/returns/new">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(main)/returns/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(main)/returns/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/returns">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(main)/returns/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(main)/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/settings">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(main)/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(main)/stock/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/stock">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(main)/stock/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(public)/cart/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/cart">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(public)/cart/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(public)/shop/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/shop/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(public)/shop/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(public)/shop/order-type/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/shop/order-type">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(public)/shop/order-type/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(public)/shop/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/shop">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(public)/shop/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(public)/support/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/support">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(public)/support/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/products/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/products">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/products/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ai/chat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/chat">> = Specific
  const handler = {} as typeof import("../../src/app/api/ai/chat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ai/embed/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/embed">> = Specific
  const handler = {} as typeof import("../../src/app/api/ai/embed/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ai/search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/search">> = Specific
  const handler = {} as typeof import("../../src/app/api/ai/search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/[...nextauth]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/[...nextauth]">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/[...nextauth]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/otp/send-email/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/otp/send-email">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/otp/send-email/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/otp/send/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/otp/send">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/otp/send/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/otp/verify-firebase/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/otp/verify-firebase">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/otp/verify-firebase/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/otp/verify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/otp/verify">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/otp/verify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/webauthn/auth-options/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/webauthn/auth-options">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/webauthn/auth-options/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/webauthn/auth-verify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/webauthn/auth-verify">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/webauthn/auth-verify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/webauthn/register-options/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/webauthn/register-options">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/webauthn/register-options/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/webauthn/register-verify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/webauthn/register-verify">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/webauthn/register-verify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/checkout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/checkout">> = Specific
  const handler = {} as typeof import("../../src/app/api/checkout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/error-report/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/error-report">> = Specific
  const handler = {} as typeof import("../../src/app/api/error-report/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health">> = Specific
  const handler = {} as typeof import("../../src/app/api/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/images/[itemId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/images/[itemId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/images/[itemId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/mobile/auth/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mobile/auth/callback">> = Specific
  const handler = {} as typeof import("../../src/app/api/mobile/auth/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/mobile/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mobile/auth/login">> = Specific
  const handler = {} as typeof import("../../src/app/api/mobile/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/mobile/auth/session/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mobile/auth/session">> = Specific
  const handler = {} as typeof import("../../src/app/api/mobile/auth/session/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/mobile/auth/verify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mobile/auth/verify">> = Specific
  const handler = {} as typeof import("../../src/app/api/mobile/auth/verify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/mobile/cart/checkout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mobile/cart/checkout">> = Specific
  const handler = {} as typeof import("../../src/app/api/mobile/cart/checkout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/mobile/categories/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mobile/categories">> = Specific
  const handler = {} as typeof import("../../src/app/api/mobile/categories/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/mobile/credit-notes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mobile/credit-notes">> = Specific
  const handler = {} as typeof import("../../src/app/api/mobile/credit-notes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/mobile/dashboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mobile/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/api/mobile/dashboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/mobile/invoices/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mobile/invoices/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/mobile/invoices/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/mobile/invoices/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mobile/invoices">> = Specific
  const handler = {} as typeof import("../../src/app/api/mobile/invoices/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/mobile/orders/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mobile/orders/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/mobile/orders/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/mobile/orders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mobile/orders">> = Specific
  const handler = {} as typeof import("../../src/app/api/mobile/orders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/mobile/payments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mobile/payments">> = Specific
  const handler = {} as typeof import("../../src/app/api/mobile/payments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/mobile/products/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mobile/products/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/mobile/products/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/mobile/products/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mobile/products">> = Specific
  const handler = {} as typeof import("../../src/app/api/mobile/products/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/mobile/profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mobile/profile">> = Specific
  const handler = {} as typeof import("../../src/app/api/mobile/profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/mobile/statement/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mobile/statement">> = Specific
  const handler = {} as typeof import("../../src/app/api/mobile/statement/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notifications/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications">> = Specific
  const handler = {} as typeof import("../../src/app/api/notifications/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/orders/[orderId]/approve/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/[orderId]/approve">> = Specific
  const handler = {} as typeof import("../../src/app/api/orders/[orderId]/approve/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/orders/[orderId]/delivery-confirm/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/[orderId]/delivery-confirm">> = Specific
  const handler = {} as typeof import("../../src/app/api/orders/[orderId]/delivery-confirm/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/orders/[orderId]/receive/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/[orderId]/receive">> = Specific
  const handler = {} as typeof import("../../src/app/api/orders/[orderId]/receive/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/orders/[orderId]/reject/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/[orderId]/reject">> = Specific
  const handler = {} as typeof import("../../src/app/api/orders/[orderId]/reject/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/returns/submit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/returns/submit">> = Specific
  const handler = {} as typeof import("../../src/app/api/returns/submit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/revalidate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/revalidate">> = Specific
  const handler = {} as typeof import("../../src/app/api/revalidate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/stock/search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stock/search">> = Specific
  const handler = {} as typeof import("../../src/app/api/stock/search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/sync/images/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sync/images">> = Specific
  const handler = {} as typeof import("../../src/app/api/sync/images/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/sync/stock/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sync/stock">> = Specific
  const handler = {} as typeof import("../../src/app/api/sync/stock/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/[locale]/(auth)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(auth)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(main)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(main)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(public)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(public)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
